function y = BRUDNOPISOWY(x)
%BRUDNOPISOWY Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 12-Apr-2018 08:31:16

persistent Hd;

if isempty(Hd)
    
    Fpass = 5;    % Passband Frequency
    Fstop = 10;    % Stopband Frequency
    Apass = 1;     % Passband Ripple (dB)
    Astop = 80;    % Stopband Attenuation (dB)
    Fs    = 1000;  % Sampling Frequency
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


