function y = filtering_highpass(x)
%FILTERING_HIGHPASS Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 19-Mar-2018 12:05:29

persistent Hd;

if isempty(Hd)
    
    Fstop = 20;  % Stopband Frequency
    Fpass = 50;  % Passband Frequency
    Astop = 60;  % Stopband Attenuation (dB)
    Apass = 1;   % Passband Ripple (dB)
    Fs    = fs;  % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


