function y = filtering_lowpass(x,fs)
%FILTERING Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 19-Mar-2018 12:03:21

persistent Hd;

if isempty(Hd)
    
    Fpass = 20;  % Passband Frequency
    Fstop = 50;  % Stopband Frequency
    Apass = 1;   % Passband Ripple (dB)
    Astop = 60;  % Stopband Attenuation (dB)
    Fs    = fs;  % Sampling Frequency
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


